services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
      - ./scripts:/home/student/mongodb

volumes:
  mongo_data:
